server:
  port: 8712
spring:
  application:
    name: scheduler-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka/

#注意：上面这些与spring-cloud相关的属性必须配置在bootstrap.properties中，config部分内容才能被正确加载。
#因为config的相关配置会先于application.properties，而bootstrap.properties的加载也是先于application.yml。

# hystrix熔断
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        #这里的超时时间和熔断的超时时间是分开的，这里的是指客户端超时时间，hystrix里的指规定timeoutInMilliseconds时间超时后跳转到熔断页面
        connectTimeout: 60000
        readTimeout: 60000
hystrix:
  command:
    default:
      circuitBreaker:
        #enabled: false  #不开启熔断
        requestVolumeThreshold: 75 #一个统计窗口内熔断触发的最小个数
        sleepWindowInMilliseconds: 5000  #熔断多少秒后去尝试请求
        errorThresholdPercentage: 75  #失败率达到多少百分比后熔断
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            #时间超时后跳转到熔断页面
            timeoutInMilliseconds: 60000