server:
  port: 8712
spring:
  application:
    name: scheduler-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka/

#注意：上面这些与spring-cloud相关的属性必须配置在bootstrap.properties中，config部分内容才能被正确加载。
#因为config的相关配置会先于application.properties，而bootstrap.properties的加载也是先于application.yml。

# hystrix熔断
feign:
  hystrix:
    enabled: true
